### ISSUE TITLE
应用安装成功后无法启动

### ISSUE THREAD

**Issue by kite8** [vicedev/ZY-Player-Android#1]
非常感谢作者，我手里有两部手机,一部可以正常使用(安卓7.0, miui 9.8.3.22开发版)，一部无法启动应用(点击应用没有反应)，这部手机的安卓内核是8.0，MIUI 10.3稳定版；如果还需要什么信息，请直接说。

**Comment by vicedev** [comment]
试下我刚上传的版本，可能是因为我没在manifest中配置权限的缘故

**Comment by vicedev** [comment]
> 非常感谢作者，我手里有两部手机,一部可以正常使用(安卓7.0, miui 9.8.3.22开发版)，一部无法启动应用(点击应用没有反应)，这部手机的安卓内核是8.0，MIUI 10.3稳定版；如果还需要什么信息，请直接说。

试下我刚上传的版本，可能是因为我没在manifest中配置权限的缘故

**Comment by kite8** [comment]
我刚刚试了下，发现还是不行...

**Comment by vicedev** [comment]
> 我刚刚试了下，发现还是不行...

可以加下微信吗 qiu951001 ，这问题比较奇怪，我这拿不到具体的log也没办法排查

**Comment by vicedev** [comment]
感谢反馈，已发布新版本修复
