### ISSUE TITLE
大部分资源站的xml api接口存在需要处理倒序或者正序的问题。

### ISSUE THREAD

**Issue by linsongze** [vicedev/ZY-Player-Android#12]
哈哈，终于看到你更新了，挺开心的。
我觉得这些xml资源站存在着一个很蛋疼的问题，就是排序的问题，我们浏览视频列表，肯定是最新的在最上面，，但是他们的xml默认都是返回最早的数据。
其实之前我拿你旧的版本也集成了这些xml资源站。但是我没找到排序的参数，最后我发现需要去人工去标记每个资源站是正序或者倒序，而且能够在切换类目的时候get category的max page，翻页实行-1 的那种倒过来翻页的查询。。。有点蛋疼。。
不知道你那边有没有找到其他更好的解决方案。

**Comment by vicedev** [comment]
一直没有注意到这个问题.。。。
具体方案得再去研究研究了。。。

**Comment by vicedev** [comment]
> 哈哈，终于看到你更新了，挺开心的。
> 我觉得这些xml资源站存在着一个很蛋疼的问题，就是排序的问题，我们浏览视频列表，肯定是最新的在最上面，，但是他们的xml默认都是返回最早的数据。
> 其实之前我拿你旧的版本也集成了这些xml资源站。但是我没找到排序的参数，最后我发现需要去人工去标记每个资源站是正序或者倒序，而且能够在切换类目的时候get category的max page，翻页实行-1 的那种倒过来翻页的查询。。。有点蛋疼。。
> 不知道你那边有没有找到其他更好的解决方案。

一直没有注意到这个问题.。。。
具体方案得再去研究研究了。。。
