### ISSUE TITLE
大佬，自定义视频源是关键啊，希望尽快更新，这个才是软件的灵魂，能告诉我怎么临时添加源吗？

### ISSUE THREAD

**Issue by andylhj** [vicedev/ZY-Player-Android#13]

**Comment by vicedev** [comment]
自定义源在规划中，你想临时添加的话需要修改 assets中的SourceConfig.txt文件，再重新打包，也就是直接修改了内置的源

**Comment by vicedev** [comment]
@andylhj  自定义源在规划中，你想临时添加的话需要修改 assets中的SourceConfig.txt文件，再重新打包，也就是直接修改了内置的源

**Comment by vicedev** [comment]
已支持

**Comment by ChaoyuanJam** [comment]
作者可以说一下具体Android添加视频源的方法么
