### ISSUE TITLE
[建议]希望可以增加局域网投屏功能！

### ISSUE THREAD

**Issue by emengweb** [vicedev/ZY-Player-Android#24]
虽然不能直接在TV上安装使用，但是还是希望可以支持投屏，这样就可以投屏到电视上看啦！ 0v0

**Comment by luckerbai** [comment]
> 虽然不能直接在TV上安装使用，但是还是希望可以支持投屏，这样就可以投屏到电视上看啦！ 0v0

看到有在todo list 上
