### ISSUE TITLE
华为手机报病毒

### ISSUE THREAD

**Issue by lcl0512** [vicedev/ZY-Player-Android#26]
使用手机荣耀20 pro
ZY-Player版本2.4.3
病毒类型：Trojan.Generic
![Screenshot_20201222_181443_com huawei systemmanag](https://user-images.githubusercontent.com/48338140/102877662-11ccbe00-4482-11eb-9045-6aed47cf5a3f.jpg)
![Screenshot_20201222_181455_com huawei systemmanag](https://user-images.githubusercontent.com/48338140/102877665-12fdeb00-4482-11eb-9f1c-d8db7a6b7a9a.jpg)
![Screenshot_20201222_181509_com vicedev zy_player_](https://user-images.githubusercontent.com/48338140/102877666-13968180-4482-11eb-8e9c-c35c605471af.jpg)

**Comment by vicedev** [comment]
> 使用手机荣耀20 pro
> ZY-Player版本2.4.3
> 病毒类型：Trojan.Generic
> ![Screenshot_20201222_181443_com huawei systemmanag](https://user-images.githubusercontent.com/48338140/102877662-11ccbe00-4482-11eb-9045-6aed47cf5a3f.jpg)
> ![Screenshot_20201222_181455_com huawei systemmanag](https://user-images.githubusercontent.com/48338140/102877665-12fdeb00-4482-11eb-9f1c-d8db7a6b7a9a.jpg)
> ![Screenshot_20201222_181509_com vicedev zy_player_](https://user-images.githubusercontent.com/48338140/102877666-13968180-4482-11eb-8e9c-c35c605471af.jpg)

最近群里也有很多用户反馈这个问题，都是华为手机，不用理他。。。估计没上应用市场就报这个，担心有问题的可以把应用的权限都给关了就行了。
