### ISSUE TITLE
大佬，可以做个TV盒子版的吗，谢谢

### ISSUE THREAD

**Issue by iy1024** [vicedev/ZY-Player-Android#27]
大佬，可以做个TV盒子版的吗，谢谢

**Comment by Jiyue-Qin** [comment]
> 大佬，可以做个TV盒子版的吗，谢谢

https://github.com/cuiocean/ZY-Player-TV 有人在做了，但是好像还在进行中

**Comment by wuwujia** [comment]
支持啊，需要盒子版本的

**Comment by vicedev** [comment]
盒子找别人写的版本吧，我应该不会做盒子的
