### ISSUE TITLE
刚试用了一下，感觉很棒

### ISSUE THREAD

**Issue by irealshow** [vicedev/ZY-Player-Android#6]
刚试用了一下，感觉很棒，坐等新版上线

**Comment by vicedev** [comment]
> 刚试用了一下，感觉很棒，坐等新版上线

谢谢~今天有点丧，看到你的评论很开心。
这段时间有点忙，空下来会再更新的，谢谢支持~

**Comment by vicedev** [comment]
> 刚试用了一下，感觉很棒，坐等新版上线

谢谢，今天有点丧，看到你的评论很开心。
这段时间有点忙，空下来会再更新的，谢谢支持。
