### ISSUE TITLE
这是放弃开发了吗？2个月没有更新了

### ISSUE THREAD

**Issue by bebestmaple** [vicedev/ZY-Player-Android#9]

**Comment by zero-hugo** [comment]
可能。我也是惦记着，时不时来看看有没有更新，但一点动静没有。

**Comment by vicedev** [comment]
@bebestmaple @zero-hugo   感谢关注，这段时间工作太忙了，近期打算开始开发下一版本

**Comment by bebestmaple** [comment]
感谢开发者的贡献，只是提个建议，当长时间不更新时，可以在readme上写一下。感谢！

**Comment by vicedev** [comment]
@bebestmaple @zero-hugo 感谢支持~新版出来咯，可以试用一下
